# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bb476ac6d4ccfcc90bde85968e6c2cc2199f4ab6543a73cd7dff99851116c6a50ce769072f1cea2c8cea0aa93304c377cf2848d3badf5db21fb5e700da4b8e5

test:
  secret_key_base: c84195d3d7d13b7d7c84a6b144ba9058e18af89ba924a952425c5e8c8b280497a95582e387a2551250a2093dcd266e10c07fc43d33b07b6293f3d6275292df5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
